#!/bin/sh /etc/rc.common
# Copyright (c) 2014 The Linux Foundation. All rights reserved.
# Copyright (C) 2010-2014 OpenWrt.org

START=99
STOP=10



igmp_add_fw_rules() {
	local r1 r2 r3
	
	r1=$(fw list 4 f zone_wan|grep "\-p igmp")
	[ -z "$r1" ] && fw add 4 f zone_wan ACCEPT ^ { -p igmp }
	
	r2=$(fw list 4 f zone_wan|grep "\-d 224.0.0.0/4")
	[ -z "$r2" ] && fw add 4 f zone_wan ACCEPT ^ { -p udp -d 224.0.0.0/4 }
	
	r3=$(fw list 4 f zone_wan_forward|grep "\-d 224.0.0.0/4")
	[ -z "$r3" ] && fw add 4 f zone_wan_forward zone_lan_ACCEPT ^ { -p udp -d 224.0.0.0/4 }
}

igmp_del_fw_rules() {
	fw del 4 f zone_wan ACCEPT { -p igmp }
	fw del 4 f zone_wan ACCEPT { -p udp -d 224.0.0.0/4 }
	fw del 4 f zone_wan_forward zone_lan_ACCEPT { -p udp -d 224.0.0.0/4 }
}



start() {

	local sysmode
	config_load sysmode
	config_get sysmode sysmode mode "router"
	if [ "$sysmode" = "ap" ]; then
		return 0
	fi

	local udproxy_enable
	local udp_proxy
	local wan_if
	local improxy_enable
	config_load iptv
	
	config_get udp_proxy "iptv" udp_proxy
	config_get improxy_enable "iptv" igmp_enable
	config_get udproxy_enable "iptv" udp_proxy_enable 
	#config_get wan_if "iptv" wan
	#wan_if=$(uci get protocol.wan.ifname)

	if [ "$udproxy_enable" = "on" ]; then
		
		service_start /usr/sbin/udpxy -p $udp_proxy -B 1Mb -a br-lan  -R -1 -c 10
		igmp_add_fw_rules
	else if [ "$improxy_enable" != "on" ]; then
		igmp_del_fw_rules	
	     fi
	fi

	return 0
}

stop() {
	local sysmode
	config_load sysmode
	config_get sysmode sysmode mode "router"
	if [ "$sysmode" = "ap" ]; then
		return 0
	fi	
	service_stop /usr/sbin/udpxy
	return 0
}
